#!/bin/sh

# t2 - PLACEMENT DAY
#
# Usage: t2 PLACEMENT [tile_gap]

# Preliminaries ###############################################################

CONFIG_DIR="${HOME}/.config/t2"

usage () {
  cat <<-EOF
	Usage:
	  ${0##*/} [-c CONFIG_FILE_SUFFIX] LAYOUT

	Options:

	-c CONFIG_FILE_SUFFIX
	  Use an alternate config file to place the active window
	  "-c 2" sources \${HOME}/.config/t2/layout-2

	LAYOUT
	  A 4-char argument formatted [TILES][X_0][X_1][Y_SPAN]

	  TILES
	    [0-9] slice screen into TILES vertical sections

	  X_0
	    [0-9] Window's left edge is left boundary of tile X_0

	  X_1
	    [0-9] Window's right edge is right boundary of tile X_1

	  Y_SPAN
	    [fhl] Place across full, upper half, or lower half of
	    the tile space
EOF
}

_AWIN=$(xdotool getactivewindow getwindowname)

# Fallback to make sure we don't accidentally tile the desktop window.
# Supports MATE and Xfce so far.
if [[ "$_AWIN" = "x-caja-desktop" || "$_AWIN" = "Desktop" ]]
then
  echo "Yeah, not movin' that one."
  exit 2
fi

# Config - Change these to match your own environment #########################

while getopts :c: o; do
  case "${o}" in
    c)
      if [[ -e "${CONFIG_DIR}/layout-${OPTARG}" ]]; then
        CONFIG_FILE="${CONFIG_DIR}/layout-${OPTARG}"
        . $CONFIG_FILE
      else
	echo "Unable to locate ${CONFIG_DIR}/layout-${OPTARG}."
        exit 3
      fi
      ;;
  esac
done

if [[ -z "${CONFIG_FILE+x}" ]]; then
  CONFIG_FILE="${CONFIG_DIR}/layout"
  . $CONFIG_FILE
fi

# You guessed it.
screen_width=$(( $mon_width - $left_margin - $right_margin ))

screen_height=$(( $mon_height - $top_panel_height - $bottom_panel_height - \
$top_margin - $bottom_margin ))

# Tiling preferences ##########################################################

_placement="${@:$#}"

# [1-9] Number of horizontal tile slices
divs=${_placement:0:1}

# [1-9] First horizontal slice to occupy
x0=$(( ${_placement:1:1} - 1 ))

# [1-9] Last horizontal slice to occupy
# (Note that the script will fail out if $x0 > $x1.
# $x0 = $x1 is acceptable and gives a single-slice-width
# window.
x1=$(( ${_placement:2:1} - 1 ))

# [fhl] Vertical placement
# h=higher half-screen
# l=lower half-screen
# f=fullscreen
# Note that fullscreen-tiled is _not_ the same thing
# as fullscreening a window according to your tile
# manager.
case "${_placement:3:1}" in
  h)
    y0=0
    y1=0
    ;;
  l)
    y0=1
    y1=1
    ;;
  f)
    y0=0
    y1=1
    ;;
esac

if [ ! -z "$2" ]
then
  tile_gap="$2"
fi

# Window Placement ############################################################

# Basic (/single-)tile width.
tile_width=$(( $(( $screen_width / $divs )) - $(( $(( $divs - 1 )) * \
$tile_gap )) / $divs ))

# Horizontal placement of the left edge.
c=$(( $x0 * $(( $tile_width + $tile_gap )) ))
width=$(( $(( $x1 - $x0 )) * $(( $tile_width + $tile_gap )) + $tile_width ))

# Basic (/single-)tile height.
tile_height=$(( $(( $screen_height / 2 )) - $tile_gap / 2 ))

#Vertical placement of the upper edge.
d=$(( $y0 * $(( $tile_height + $tile_gap )) ))
height=$(( $(( $y1 - $y0 )) * $(( $tile_height + $tile_gap )) + $tile_height ))

echo $width $height $c $d

xdotool getactivewindow windowsize $width $height windowmove \
$(( $c + $left_margin + $horizontal_offset )) \
$(( $d + $top_panel + $top_margin + $vertical_offset ))

unset width height c d

exit 0
